# These are supported funding model platforms

github: jdnichollsc
patreon: proyecto26
open_collective: proyecto26
ko_fi: proyecto26
tidelift: "npm/@ion-phaser/core"
liberapay: proyecto26
custom: "https://www.paypal.me/jdnichollsc"
